### ISSUE TITLE
Can't place minion if in second hand (minion is lost after placing it)

### ISSUE THREAD

**Issue by freddycor** [Artillex-Studios/AxMinions#11]
Hi, I'm using AxMinions and I found a bug that makes the player lose their minion.

If you hold your minion with the left hand (I'm currently in 1.20.4), if you right click with nothing in the right hand, it will place the skull but not the minion. Then, when you take back the skull it becomes a normal skull and you lost your minion.
I think it's quite easy to fix, checking the second hand too when you listen the event to place the minion.

P.S. This plugin is so good, keep going!

**Comment by AverageGithub** [comment]
Thank you for reporting! I fixed it, will be releasing a new version soon!
