### ISSUE TITLE
 Add detection for the generator (stairs waterlogged)

### ISSUE THREAD

**Issue by Weyl1** [Artillex-Studios/AxMinions#24]
Add detection for the generator (stairs waterlogged)
![2024-07-29_12 51 30](https://github.com/user-attachments/assets/10cef727-7af0-47b2-9147-59ea30cbbf29)

The miner minion does not detect this type of generator

**Comment by AverageGithub** [comment]
Support for this was added really early on in like 1.0.2, but on this screenshot it seems like your minion does not have a tool, couldn't that be the issue?

**Comment by Weyl1** [comment]
Oh sorry, you're right.
