### ISSUE TITLE
Getting disconnected error from right & left click

### ISSUE THREAD

**Issue by NeuroSMP** [Artillex-Studios/AxMinions#4]
I am just playing around with some minions and I have found that if my ALT right or left clicks my minion in a claim they get kicked off the server.

**17.03 16:55:46 [Disconnect] User NeuroSB has disconnected, reason: Internal Exception: java.lang.IllegalStateException: ClaimPermissionCheckEvent may only be triggered synchronously.**

I am using GriefPrevention and was in my claim and my alt isn't trusted in the claim.

No claim around minions = no kick
Trust ALT in claim = kick error
Claimed land no trust ATL = kick error

Version: 1.0.6
Java 17

![image](https://github.com/Artillex-Studios/AxMinions/assets/163584065/40d6228d-a30c-4b73-9aea-8b3be3d62d54)
![image](https://github.com/Artillex-Studios/AxMinions/assets/163584065/0b029b51-99a5-4368-91e5-997d25a10e55)

**Comment by AverageGithub** [comment]
I'm sorry that I didn't respond earlier. 

I've found the issue and I will soon release a version with this issue fixed!
